FROM node:16 as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx 
EXPOSE 3001
COPY ./nginx/local.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/build /usr/share/nginx/html
