version: "3.8"
services:
    nginx:
      depends_on:
        - frontend
        - backend
      restart: always # because it is routing traffic to our entire app
      build:
        dockerfile: Dockerfile.dev
        context: ./nginx
      ports:
        - '80:80'
      networks:
        - app-network
    frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile.dev
      ports:
      - '3001:3001'
      volumes:
        - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
        - ./frontend:/app
      restart: on-failure
      container_name: frontend
      environment:
        - EXPRESS_HOST=backend
      networks:
        app-network:
    backend:
      build:
        context: ./backend
        dockerfile: Dockerfile.dev
      ports:
      - '4001:4001'
      restart: on-failure
      container_name: backend
      volumes:
        - /app/node_modules # Inside the container, don't try to override this folder, just leave as is
        - ./backend:/app
      networks:
        app-network:
    mongo:
      image: 'mongo'
      container_name: 'mongo-db'
      restart: always
      ports:
        - '27017:27017'
      volumes: 
        - dbdata:/data/db
      networks:
        - app-network

networks:
  app-network:
    driver: bridge
volumes:
  dbdata: